        DROP DATABASE BALTRETAIL;
        CREATE DATABASE IF NOT EXISTS BALTRETAIL;
        USE BALTRETAIL;

        CREATE TABLE CLIENTES(
        ID_CLIENTE VARCHAR(33) COMMENT 'MD5 DEL CAMPO IDENTIDAD, IDENTIFICADOR DEL CLIENTE',
        NOMBRE VARCHAR(80) NOT NULL COMMENT 'Nombre del cliente',
        APELLIDOS VARCHAR(160) COMMENT 'APELLIDOS DEL CLIENTE',
        TIPO_DOCUMENTO ENUM('NIF','CIF') NOT NULL COMMENT 'PERSONA O EMPRESA',
        IDENTIDAD VARCHAR(9) NOT NULL UNIQUE COMMENT 'NIF O NIE DEL CLIENTE', 
        CORREO VARCHAR(120) COMMENT 'CORREO DEL CLIENTE', 
        TELEFONO VARCHAR(15) COMMENT 'TELEFONO DEL CLIENTE',
        MOROSO BOOLEAN COMMENT 'FALSE = NO MOROSO, TRUE=MOROSO',
        ALTA DATE NOT NULL COMMENT 'FECHA DE ALTA DEL CLIENTE',
        MODIFICACION DATETIME NOT NULL COMMENT 'FECHA DE ULTIMA MODIFICACION DEL CLIENTE',
        CONSTRAINT CLIENTES_PK PRIMARY KEY (ID_CLIENTE)
        )COMMENT='TABLA DE CLIENTES';

        CREATE TABLE EMPLEADOS(
        ID_EMPLEADO VARCHAR(33) COMMENT 'CODIGO INTERNO DEL EMPLEADO, MD5 DEL CAMPO IDENTIDAD',
        NOMBRE VARCHAR(80) NOT NULL COMMENT 'NOMBRE DEL EMPLEADO',
        APELLIDOS VARCHAR(160) NOT NULL COMMENT 'APELLIDOS DEL EMPLEADO',
        IDENTIDAD VARCHAR(9) NOT NULL UNIQUE COMMENT 'NIF O NIE DEL EMPLEADO', 
        CORREO VARCHAR(120) NOT NULL COMMENT 'CORREO DEL EMPLEADO', 
        TELEFONO VARCHAR(15) NOT NULL COMMENT 'TELEFONO DEL EMPLEADO',
        NACIMIENTO DATE NOT NULL COMMENT 'FECHA DE NACIMIENTO DEL EMPLEADO',
        ALTA DATE NOT NULL COMMENT 'FECHA DE ALTA DEL EMPLEADO',
        CONTRASEÑA VARCHAR(60) NOT NULL UNIQUE COMMENT 'MD5 DE LA CONTRASEÑA DEL USUARIO',
        CARGO ENUM('EMPLEADO','GERENTE','ADMINISTRADOR') NOT NULL COMMENT 'CARGO DENTRO DE LA EMPRESA DEL EMPLEADO',
        MODIFICACION DATETIME NOT NULL COMMENT 'FECHA ULTIMA MODIFICACION DEL EMPLEADO',
        CONSTRAINT EMPLEADOS_PK PRIMARY KEY (ID_EMPLEADO)
        )COMMENT='TABLA DE EMPLEADOS';

        CREATE TABLE ARTICULOS (
        ID_ARTICULO VARCHAR(33)  COMMENT 'PRIMARY KEY Identificador único del artículo, MD5 del campo nombre',
        NOMBRE VARCHAR(100) NOT NULL COMMENT 'Nombre del artículo',
        DESCRIPCION TEXT COMMENT 'Comentario del artículo para su descripción al público',
        PRECIO DECIMAL(10,2) NOT NULL COMMENT 'Precio final del artículo',
        CREACION DATETIME NOT NULL COMMENT 'Fecha de creación del artículo',
        ACTUALIZACION DATETIME NOT NULL COMMENT 'Fecha de último cambio del artículo',
        PESO DECIMAL(10,2) COMMENT 'Peso del artículo',
        DIMENSIONES VARCHAR(100) COMMENT 'Dimensiones tipo AAxLLxFF (alto, largo y fondo)',
        DESCUENTO DECIMAL(4) DEFAULT 0 COMMENT 'PORCENTAJE DE DESCUENTO  EJEMPLO: 12,02',
        UBICACION VARCHAR(10) COMMENT 'CÓDIGO DE LA UBICACIÓN',
        DISPONIBILIDAD BOOLEAN NOT NULL COMMENT 'TRUE QUEDA STOCK, FALSE NO QUEDA STOCK',
        GARANTIA INT COMMENT 'Garantía en días, si es un año 365',
        COMENTARIO TEXT COMMENT 'Comentarios de fábrica',
        IMPUESTO DECIMAL(5,2) DEFAULT 0 COMMENT 'Dato porcentual',
        CONSTRAINT ARTICULOS_PK PRIMARY KEY (ID_ARTICULO)
        )COMMENT='Tabla de artículos'; 

        CREATE TABLE MESAS(
        MESA VARCHAR(4) COMMENT 'NUMERO DE MESA',
        NOMBRE VARCHAR(150) COMMENT 'ALIAS DE LA MESA',
        MAX_COMENSALES INT COMMENT 'NUMERO MAXIMO DE COMENSALES',
        MIN_COMENSALES INT COMMENT 'NUMERO MINIMO DE COMENSALES',
        OCUPADA BOOLEAN COMMENT 'TIENE CLIENTES EN EL MOMENTO O ESTA LIBRE',
        UBICACION ENUM ('SALON 1','SALON 2', 'TERRAZA 1', 'TERRAZA 2'),
        TIPO_MESA ENUM ('ALTA', 'COMEDOR', 'CHILLOUT'),
        NOTAS TEXT COMMENT 'NOTAS SOBRE LA MESA',
        CONSTRAINT MESAS_PK PRIMARY KEY (MESA)
        )COMMENT='TABLA EN LA QUE SE REGISTRAN LOS DATOS DE CADA MESA';

        CREATE TABLE CARRITOS(
        MESA VARCHAR(4) COMMENT 'NUMERO DE MESA',
        INSERCION DATETIME COMMENT 'FECHA Y HORA DE INSERCION',
        ID_ARTICULO VARCHAR(33) NOT NULL COMMENT 'PRIMARY KEY Identificador único del artículo, MD5 del campo nombre',
        CANTIDAD INT NOT NULL COMMENT 'CANTIDAD DEL ARTICULO',
        DESCUENTO DECIMAL (5,2) COMMENT 'DESCUENTO DE LA LINEA',
        CONSTRAINT CARRITOS_PK PRIMARY KEY (MESA, ID_ARTICULO),
        CONSTRAINT CARRITOS_ART_FK FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULOS (ID_ARTICULO),
        CONSTRAINT CARRITOS_MESAS_FK FOREIGN KEY (MESA) REFERENCES MESAS (MESA)
        )COMMENT='TABLA PARA GESTIONAR LO QUE SE ESTA PIDIENDO EN EL MOMENTO';

        CREATE TABLE RESERVAS(
        ID_RESERVA INT AUTO_INCREMENT COMMENT 'CODIGO DE RESERVA',
        MESA VARCHAR(4) COMMENT 'NUMERO DE MESA',
        INICIO_RESERVA DATETIME NOT NULL COMMENT 'FECHA Y HORA DE INICIO DE LA RESERVA',
        FIN_RESERVA DATETIME NOT NULL COMMENT 'FECHA Y HORA DE FIN DE RESERVA',
        ID_CLIENTE VARCHAR(33) COMMENT 'MD5 DEL CAMPO IDENTIDAD, IDENTIFICADOR DEL CLIENTE',
        ID_EMPLEADO VARCHAR(33) COMMENT 'CODIGO INTERNO DEL EMPLEADO, MD5 DEL CAMPO IDENTIDAD',
        NUM_PERSONAS INT COMMENT 'PERSONAS QUE ACUDIRAN A LA RESERVA',
        ESTADO ENUM ('PENDIENTE','CONFIRMADA','EN ESPERA','CHECK-IN','COMPLETADA','CANCELADA','NO SHOW','MODIFICADA','RECHAZADA') NOT NULL,
        TELEFONO VARCHAR(15) NOT NULL COMMENT 'TELEFONO DE LA PERSONA QUE HIZO LA RESERVA',
        NOTAS_CLIENTE VARCHAR(255) COMMENT 'NOTAS DEL CLIENTE, INTOLERACIAS, PETICIONES...',
        NOTAS_EMPLEADOS VARCHAR(255) COMMENT 'NOTAS DE LOS CAMAREROS',
        FECHA_CREACION DATETIME NOT NULL COMMENT 'FECHA Y HORA EN LA QUE SE HIZO LA RESERVA',
        FECHA_MODIFICACION DATETIME NOT NULL COMMENT 'FECHA Y HORA DE ULTIMA MODIFICACION',
        CONSTRAINT RESERVAS_PK PRIMARY KEY (ID_RESERVA),
        CONSTRAINT RESERVAS_CLIENTES_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
        CONSTRAINT RESERVAS_EMPLEADOS_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO),
        CONSTRAINT RESERVAS_MESAS_FK FOREIGN KEY (MESA) REFERENCES MESAS (MESA)
        );

        CREATE TABLE PEDIDOS(
        ID_PEDIDO INT AUTO_INCREMENT COMMENT 'CODIGO DE PEDIDO',
        ID_CLIENTE VARCHAR(33) COMMENT 'MD5 DEL CAMPO IDENTIDAD.CLIENTES, IDENTIFICADOR DEL CLIENTE',
        ID_EMPLEADO VARCHAR(33) COMMENT 'CODIGO INTERNO DEL EMPLEADO, MD5 DEL CAMPO IDENTIDAD',
        MESA VARCHAR(4) COMMENT 'NUMERO DE MESA',
        FECHA_COMPRA DATETIME NOT NULL COMMENT 'FECHA DE COMPRA DEL PEDIDO',
        ESTADO ENUM ('PENDIENTE','PAGADO','IMPAGADO') NOT NULL COMMENT 'ESTADO DEL PEDIDO',
        NOTA_PEDIDO TEXT COMMENT 'NOTA INTERNA DEL PEDIDO',
        INICIO_PREPARACION DATETIME  COMMENT 'MOMENTO DE LA PREPARACION',
        FIN_PREPARACION DATETIME COMMENT 'FIN DE LA PREPARACION',
        TOTAL_PAGADO DECIMAL(10,2) NOT NULL COMMENT 'TOTAL PAGADO DEL PEDIDO',
        FECHA_PAGO DATETIME NOT NULL COMMENT 'FECHA DE PAGO DEL PEDIDO',
        TOTAL DECIMAL(10,2) NOT NULL COMMENT 'PRECIO TOTAL DEL PEDIDO',
        DESCUENTO DECIMAL (5,2) COMMENT 'DESCUENTO APLICADO SOBRE EL PRECIO',
        COMENTARIO TEXT COMMENT 'COMENTARIO SOBRE EL PEDIDO',
        CONSTRAINT PEDIDOS_PK PRIMARY KEY (ID_PEDIDO),
        CONSTRAINT PED_CLI_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
        CONSTRAINT PED_EMP_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO),
        CONSTRAINT MESA_FK FOREIGN KEY (MESA) REFERENCES CARRITOS (MESA)
        );



        CREATE TABLE INGREDIENTES(
        ID_INGREDIENTE VARCHAR(33) COMMENT 'MD5 DEL NOMBRE',
        NOMBRE VARCHAR(200) COMMENT 'NOMBRE DEL INGREDIENTE',
        DESCRIPCION TEXT COMMENT 'DESCRIPCIÓN DEL INGREDIENTE',
        CREACION DATETIME NOT NULL COMMENT 'Fecha de creación del artículo',
        ACTUALIZACION DATETIME NOT NULL COMMENT 'Fecha de último cambio del artículo',
        PESO DECIMAL(10,2) NOT NULL COMMENT 'Peso del artículo',
        DIMENSIONES VARCHAR(100) NOT NULL COMMENT 'Dimensiones tipo AAxLLxFF (alto, largo y fondo)',
        DESCUENTO DECIMAL(4) NOT NULL COMMENT 'PORCENTAJE DE DESCUENTO  EJEMPLO: 12,02',
        UBICACION VARCHAR(10) COMMENT 'CÓDIGO DE LA UBICACIÓN',
        COMENTARIO TEXT COMMENT 'COMENTARIO DEL INGREDIENTE',
        STOCK INT COMMENT 'CANTIDAD EN STOCK',
        CONSTRAINT INGREDIENTES_PK PRIMARY KEY (ID_INGREDIENTE)
        );

        CREATE TABLE DEVOLUCIONES(
        ID_DEVOLUCION INT AUTO_INCREMENT COMMENT 'CODIGO DE DEVOLUCION',
        ID_CLIENTE VARCHAR(33) COMMENT 'MD5 DEL CAMPO IDENTIDAD.CLIENTES, IDENTIFICADOR DEL CLIENTE',
        ID_EMPLEADO VARCHAR(33) COMMENT 'CODIGO INTERNO DEL EMPLEADO, MD5 DEL CAMPO IDENTIDAD',
        ID_PEDIDO INT COMMENT 'CODIGO DE PEDIDO',
        FECHA_DEV DATETIME COMMENT 'FECHA DE LA DEVOLUCIÓN',
        ESTADO ENUM ('PENDIENTE','DEVUELTA','NO DEVUELTA') NOT NULL COMMENT 'ESTADO DE LA DEVOLUCION',
        FECHA_PETICION DATETIME NOT NULL COMMENT 'FECHA DE LA PETICION',
        MOTIVO TEXT COMMENT 'MOTIVO DE LA DEVOLUCION',
        COMENTARIO TEXT COMMENT 'COMENTARIO INTERNO',
        CONSTRAINT DEVOLUCIONES_PK PRIMARY KEY (ID_DEVOLUCION),
        CONSTRAINT DEV_CLI_FK FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES (ID_CLIENTE),
        CONSTRAINT DEV_EMP_FK FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS (ID_EMPLEADO)
        );

        CREATE TABLE LINEAS_DEVOLUCIONES(
        ID_LINEA_DEV INT AUTO_INCREMENT COMMENT 'ID DE LAS LINEAS DE DEVOLUCION',
        ID_ARTICULO VARCHAR(33) COMMENT 'PRIMARY KEY Identificador único del artículo, MD5 del campo nombre',
        ID_DEVOLUCION INT COMMENT 'CODIGO DE DEVOLUCION',
        CANTIDAD INT COMMENT 'CANTIDAD DEL ARTICULO',
        PRECIO_UNITARIO DECIMAL(10,2) COMMENT 'PRECIO UNITARIO DEL ARTICULO',
        DESCUENTO DECIMAL (5,2) COMMENT 'DESCUENTO DE LA LINEA',
        ESTADO ENUM('PENDIENTE', 'SERVIDA') NOT NULL COMMENT 'ESTADO DE LA LINEA',
        CONSTRAINT LIN_DEV_PK PRIMARY KEY (ID_LINEA_DEV, ID_ARTICULO, ID_DEVOLUCION),
        CONSTRAINT LIN_DEV_ART_FK FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULOS (ID_ARTICULO),
        CONSTRAINT LIN_DEV_DEV_FK FOREIGN KEY (ID_DEVOLUCION) REFERENCES DEVOLUCIONES (ID_DEVOLUCION)
        );

        CREATE TABLE LINEAS_PEDIDOS(
        NUM_LINEA INT COMMENT 'NUMERO DE LINEA',
        ID_ARTICULO VARCHAR(33) COMMENT 'PRIMARY KEY Identificador único del artículo, MD5 del campo nombre',
        ID_PEDIDO INT COMMENT 'CODIGO DE PEDIDO',
        CANTIDAD INT COMMENT 'CANTIDAD DEL ARTICULO',
        PRECIO_UNITARIO DECIMAL(10,2) COMMENT 'PRECIO UNITARIO DEL ARTICULO',
        DESCUENTO DECIMAL (5,2) COMMENT 'DESCUENTO DE LA LINEA',
        ESTADO ENUM('PENDIENTE', 'SERVIDA') NOT NULL COMMENT 'ESTADO DE LA LINEA',
        CONSTRAINT LIN_PED_PK PRIMARY KEY (NUM_LINEA, ID_ARTICULO, ID_PEDIDO),
        CONSTRAINT LIN_PED_ART_FK FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULOS (ID_ARTICULO),
        CONSTRAINT LIN_PED_PED_FK FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS (ID_PEDIDO)
        );

        CREATE TABLE CATEGORIAS(
        ID_CATEGORIA VARCHAR(33) COMMENT 'MD5 DEL NOMBRE DE LA CATEGORIA',
        NOMBRE VARCHAR(100) COMMENT 'NOMBRE DE LA CATEGORIA',
        FECHA_CREACION DATETIME COMMENT 'MOMENTO DE CREACION DE LA CATEGORIA',
        IMAGEN VARCHAR(255) COMMENT 'IMAGEN DE LA CATEGORIA',
        ORDEN INT NOT NULL COMMENT 'ORDEN EN EL QUE MOSTRAR EN PANTALLA',
        CONSTRAINT CATEGORIAS_PK PRIMARY KEY (ID_CATEGORIA)
        );

        CREATE TABLE SUBCATEGORIAS(
        ID_SUBCATEGORIA VARCHAR(33) COMMENT 'ID DE LA SUBCATEGORIA, MD5 DEL NOMBRE',
        ID_CATEGORIA VARCHAR(33) COMMENT 'CATEGORIA A LA QUE PERTENECE',
        NOMBRE VARCHAR(100) COMMENT 'NOMBRE DE LA SUBCATEGORIA',
        FECHA_CREACION DATETIME COMMENT 'FECHA DE CREACIÓN DE LA SUBCATEGORIA',
        IMAGEN VARCHAR(255) COMMENT 'IMAGEN DE LA SUBCATEGORIA',
        ORDEN INT NOT NULL COMMENT 'ORDEN EN EL QUE MOSTRAR EN PANTALLA',
        CONSTRAINT SUBCATEGORIAS_PK PRIMARY KEY (ID_SUBCATEGORIA,ID_CATEGORIA),
        CONSTRAINT SUBCATE_CATE_FK FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID_CATEGORIA)
        );

        CREATE TABLE SUBCAT_ART(
        ID_SUBCATEGORIA VARCHAR(33) COMMENT 'ID DE LA SUBCATEGORIA, MD5 DEL NOMBRE',
        ID_ARTICULO VARCHAR(33) COMMENT 'PRIMARY KEY Identificador único del artículo, MD5 del campo nombre',
        CONSTRAINT SUBCAT_ART_PK PRIMARY KEY (ID_SUBCATEGORIA, ID_ARTICULO),
        CONSTRAINT SUBCAT_ART_SUBCAT_FK FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES SUBCATEGORIAS (ID_SUBCATEGORIA),
        CONSTRAINT SUBCAT_ART_ART_FK FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULOS (ID_ARTICULO)
        );

        CREATE TABLE INGRED_ART(
        ID_INGREDIENTE VARCHAR(33) COMMENT 'MD5 DEL NOMBRE',
        ID_ARTICULO VARCHAR(33) COMMENT 'PRIMARY KEY Identificador único del artículo, MD5 del campo nombre',
        CONSTRAINT INGRED_ART_PK PRIMARY KEY (ID_INGREDIENTE,ID_ARTICULO),
        CONSTRAINT INGRED_ART_INGRED_FK FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTES (ID_INGREDIENTE),
        CONSTRAINT INGRED_ART_ART_FK FOREIGN KEY (ID_ARTICULO) REFERENCES ARTICULOS (ID_ARTICULO)
        );

        DELIMITER //

        CREATE TRIGGER before_categoria_insert
        BEFORE INSERT ON CATEGORIAS
        FOR EACH ROW
        BEGIN
            SET NEW.ID_CATEGORIA = MD5(NEW.NOMBRE);
        END;

        //

        DELIMITER ;

        DELIMITER //

        CREATE TRIGGER before_subcategoria_insert
        BEFORE INSERT ON SUBCATEGORIAS
        FOR EACH ROW
        BEGIN
            SET NEW.ID_SUBCATEGORIA = MD5(NEW.NOMBRE);
        END;

        //

        DELIMITER ;

        DELIMITER //

        CREATE TRIGGER before_articulo_insert
        BEFORE INSERT ON ARTICULOS
        FOR EACH ROW
        BEGIN
            SET NEW.ID_ARTICULO = MD5(NEW.NOMBRE);
        END;

        //

        DELIMITER ;

        DELIMITER //

        CREATE TRIGGER before_empleado_insert
        BEFORE INSERT ON EMPLEADOS
        FOR EACH ROW
        BEGIN
            SET NEW.ID_EMPLEADO = MD5(NEW.IDENTIDAD);
        END;

        //

        DELIMITER ;

        DELIMITER //

        CREATE TRIGGER before_pedido_insert
        BEFORE INSERT ON PEDIDOS
        FOR EACH ROW
        BEGIN
            SET NEW.FECHA_COMPRA = NOW();
        END;

        //

        DELIMITER ;

        DELIMITER //

        CREATE TRIGGER before_reservas_insert
        BEFORE INSERT ON RESERVAS
        FOR EACH ROW
        BEGIN
            SET NEW.FECHA_CREACION = NOW();
            SET NEW.FECHA_MODIFICACION = NOW();
        END;

        //

        DELIMITER ;

        DELIMITER //

        CREATE TRIGGER before_reservas_update
        BEFORE UPDATE ON RESERVAS
        FOR EACH ROW
        BEGIN
            SET NEW.FECHA_MODIFICACION = NOW();
        END;

        //

        DELIMITER ;

        DELIMITER //

            CREATE TRIGGER before_carritos_insert
            BEFORE INSERT ON CARRITOS
            FOR EACH ROW
            BEGIN
                SET NEW.INSERCION = NOW();
                SET NEW.DESCUENTO=0;
            END;

        //

        DELIMITER ;


        //VISTAS

    CREATE VIEW VCARRITO AS
    SELECT 
        C.MESA,
        C.INSERCION,
        A.NOMBRE,
        C.CANTIDAD,
        C.DESCUENTO AS DESCUENTO_LINEA,
        A.DESCUENTO AS DESCUENTO_ARTICULO,
        A.IMPUESTO,
        A.PRECIO,
        ROUND(
        (
            (
                (A.PRECIO - (A.PRECIO * (A.DESCUENTO / 100))) * C.CANTIDAD
            ) - 
            (
                ((A.PRECIO - (A.PRECIO * (A.DESCUENTO / 100))) * C.CANTIDAD) * (C.DESCUENTO / 100)
            )
        ) + 
        (
            (
                (
                    (A.PRECIO - (A.PRECIO * (A.DESCUENTO / 100))) * C.CANTIDAD
                ) - 
                (
                    ((A.PRECIO - (A.PRECIO * (A.DESCUENTO / 100))) * C.CANTIDAD) * (C.DESCUENTO / 100)
                )
            ) * (A.IMPUESTO / 100)
        ),2) AS TOTAL,
        A.DESCRIPCION,
        A.ID_ARTICULO
    FROM 
        CARRITOS C
    JOIN 
        ARTICULOS A 
    ON 
        C.ID_ARTICULO = A.ID_ARTICULO;


        CREATE VIEW VARTICULOS AS
        SELECT AR.NOMBRE AS ARTICULO, AR.PRECIO, AR.DISPONIBILIDAD,SC.NOMBRE AS SUBCATEGORIA,CA.NOMBRE AS CATEGORIA FROM CATEGORIAS CA, SUBCATEGORIAS SC, SUBCAT_ART SA, ARTICULOS AR 
        WHERE 
        CA.ID_CATEGORIA = SC.ID_CATEGORIA AND 
        SC.ID_SUBCATEGORIA = SA.ID_SUBCATEGORIA AND
        SA.ID_ARTICULO = AR.ID_ARTICULO
        ORDER BY SC.NOMBRE, AR.CREACION ASC;